# LMSupplyDepots Prometheus Configuration
# Production monitoring and metrics collection

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'lmsupplydepots-prod'
    environment: 'production'

# Rules for alerting
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    metrics_path: /metrics

  # LMSupplyDepots HostApp metrics
  - job_name: 'lmsupplydepots-hostapp'
    static_configs:
      - targets:
        - 'lmsupplydepots-hostapp-prod-1:8080'
        - 'lmsupplydepots-hostapp-prod-2:8080'
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 15s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics
    scrape_interval: 15s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']
    metrics_path: /metrics
    scrape_interval: 15s

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  # Custom AI/ML metrics
  - job_name: 'lmsupplydepots-ai-metrics'
    static_configs:
      - targets:
        - 'lmsupplydepots-hostapp-prod-1:8080'
        - 'lmsupplydepots-hostapp-prod-2:8080'
    metrics_path: /ai-metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    params:
      format: ['prometheus']

# Recording rules for performance optimization
recording_rules:
  - name: 'lmsupplydepots.rules'
    rules:
    # Request rate per minute
    - record: 'lmsupplydepots:request_rate_1m'
      expr: 'rate(http_requests_total[1m])'

    # Error rate percentage
    - record: 'lmsupplydepots:error_rate_5m'
      expr: 'rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100'

    # Response time 95th percentile
    - record: 'lmsupplydepots:response_time_p95_5m'
      expr: 'histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))'

    # AI model inference metrics
    - record: 'lmsupplydepots:inference_duration_p95_5m'
      expr: 'histogram_quantile(0.95, rate(ai_inference_duration_seconds_bucket[5m]))'

    - record: 'lmsupplydepots:inference_rate_1m'
      expr: 'rate(ai_inference_requests_total[1m])'